name: scout_pro
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Logo.png
    - assets/images/Performance.png
    - assets/images/estrategia.png

  fonts:
    - family: Days One
      fonts:
        - asset: assets/fonts/DaysOne-Regular.ttf
    - family: Carme
      fonts:
        - asset: assets/fonts/Carme-Regular.ttf