name: scout_pro
description: A new Flutter project. # Es bueno agregar una descripción
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Tu Dart 3.7.2 encaja aquí, pero es bueno usar un rango compatible más amplio

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8 

  # Firebase - ¡IMPORTANTE ACTUALIZAR ESTAS VERSIONES!
  # firebase_core: 1.10.0
  # firebase_messaging: 11.2.5
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0  # O la versión más reciente compatible

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # Asegúrate que esta carpeta exista en la raíz de tu proyecto

  fonts:
    - family: Days One
      fonts:
        - asset: assets/fonts/DaysOne-Regular.ttf
    - family: Carme
      fonts:
        - asset: assets/fonts/Carme-Regular.ttf